language: java
jdk:
    - oraclejdk8
before_install:
    - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
    - export JAVA_HOME=$JAVA8_HOME
script:
    - ./mvnw clean install
after_success:
    - ./gradlew coveralls
